services:
  - type: web
    name: tree-grid-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free